### ISSUE TITLE
Brightness not functional

### ISSUE THREAD

**Issue by AshaiRey** [connornishijima/Lixie_II#4]
Using de brightness function call does not have any effect.
To check this behavior take the count_up example and add lix.brightness(1); to the loop.
Nothing happens. The display stays at full brightness. The Lixie lib is just doing a call to FastLed but apparently there is something not passed correctly, timing issues or something else. 
When using the fastled blink example and adding the setbrightness call this working correctly. 
Used board, is a Wemos D1 mini.
I am lacking in depth knowledge here so i can't fix this.

**Comment by connornishijima** [comment]
Okay, I think I've narrowed this down.

Lixie_II doesn't use the standard FastLED class to run it's course, it uses an included variant of it called a CLEDController. (This allows you to address more than one chain of Lixies in a single Sketch)

Turns out the CLEDController class does not support the FastLED.setBrightness(); function, which normally uses high speed dithering to preserve color at lower brightnesses.

I'll likely have to manually enforce brightness mathematically in the background lix.animate() ISR every time the LEDs are updated, and just pass the lix.brightness() value to that instead. Grrr.

I'll try out a version of this tonight and follow up with you soon.

**Comment by connornishijima** [comment]
Okay, quick follow up! I've changed the code to manually enforce Lixie brightness in the ISR animation loop, without changing the external functions. Please update to 1.3.0 from this repo to use the new, working lix.brightness() functions.

However, I'll be leaving this issue open as a reminder for myself to continue researching a better alternative that combines the benefits of CLEDController's options for multiple strips and FastLED's default controller dithering options.
